spring:
  profiles:
    active: dev
  application:
    name: "graduation-project"
---

spring:
  config:
    activate:
      on-profile: dev
  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  # KAFKA
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: log-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# LOGGING PROPERTIES
logging:
  level:
    root: info
    org:
      apache: error
    com:
      bugratasdemir: debug

# SERVER PROPERTIES
server:
  port: 8082